modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "better_damage_indicator"
version = "${version}"
displayName = "Better Damage INdicator"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.better_damage_indicator]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_damage_indicator]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.better_damage_indicator]]
modId = "cloth_config"
type = "required"
versionRange = "[11.1.118,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.better_damage_indicator]]
modId = "hologram_api"
type = "required"
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "better_damage_indicator.mixins.json"
